/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea2;

import javax.swing.ImageIcon;

/**
 *
 * @author emanuel
 */
public class InterfazConvolution extends javax.swing.JFrame {

    /** Procesador para poder interactuar con la imagen. */
    ProcesadorC proC=new ProcesadorC();
    
    /**
     * Creates new form InterfazConvolution
     */
    public InterfazConvolution() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        v1 = new javax.swing.JTextField();
        v2 = new javax.swing.JTextField();
        v6 = new javax.swing.JTextField();
        v4 = new javax.swing.JTextField();
        v5 = new javax.swing.JTextField();
        v3 = new javax.swing.JTextField();
        v8 = new javax.swing.JTextField();
        v7 = new javax.swing.JTextField();
        v9 = new javax.swing.JTextField();
        v10 = new javax.swing.JTextField();
        v11 = new javax.swing.JTextField();
        v12 = new javax.swing.JTextField();
        v13 = new javax.swing.JTextField();
        v14 = new javax.swing.JTextField();
        v16 = new javax.swing.JTextField();
        v17 = new javax.swing.JTextField();
        v15 = new javax.swing.JTextField();
        v18 = new javax.swing.JTextField();
        v19 = new javax.swing.JTextField();
        v20 = new javax.swing.JTextField();
        v21 = new javax.swing.JTextField();
        v22 = new javax.swing.JTextField();
        v23 = new javax.swing.JTextField();
        v24 = new javax.swing.JTextField();
        v25 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        fact = new javax.swing.JTextField();
        bias = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Original");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Blur");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Motion Blur");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Find Edges");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Sharpen");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Embosss");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Medium");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(768, 1024));

        v1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v1.setText("0");

        v2.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v2.setText("0");

        v6.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v6.setText("0");

        v4.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v4.setText("0");

        v5.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v5.setText("0");

        v3.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v3.setText("0");

        v8.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v8.setText("0");

        v7.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v7.setText("0");

        v9.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v9.setText("0");

        v10.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v10.setText("0");

        v11.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v11.setText("0");

        v12.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v12.setText("0");

        v13.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v13.setText("0");

        v14.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v14.setText("0");

        v16.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v16.setText("0");

        v17.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v17.setText("0");

        v15.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v15.setText("0");

        v18.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v18.setText("0");

        v19.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v19.setText("0");

        v20.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v20.setText("0");

        v21.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v21.setText("0");

        v22.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v22.setText("0");

        v23.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v23.setText("0");

        v24.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v24.setText("0");

        v25.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        v25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v25.setText("0");

        jButton9.setText("Aplicar Filtro");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        fact.setText("0.0");

        bias.setText("0.0");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("FACTOR");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setText("BIAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(v1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(v3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(v4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(v5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(v21, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(v22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(v16, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(v17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(v11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(v12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(v6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(v7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(v8, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                    .addComponent(v13)
                                    .addComponent(v18)
                                    .addComponent(v23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(v9, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                    .addComponent(v14)
                                    .addComponent(v19)
                                    .addComponent(v24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(v10, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                    .addComponent(v15)
                                    .addComponent(v20)
                                    .addComponent(v25)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jButton9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fact))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bias))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(v1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(v2)
                            .addComponent(v3)
                            .addComponent(v4)
                            .addComponent(v5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(v7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(v6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(v8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(v9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(v10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(v11, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(v12)
                            .addComponent(v13)
                            .addComponent(v14)
                            .addComponent(v15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(v16, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(v17)
                            .addComponent(v18)
                            .addComponent(v19)
                            .addComponent(v20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(v21, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(v22)
                            .addComponent(v23)
                            .addComponent(v24)
                            .addComponent(v25))
                        .addGap(18, 18, 18)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(!proC.tieneImagen())
            return;
        muestraMatriz(proC.emboss1);
        jLabel1.setIcon(new ImageIcon(proC.emboss(0)));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel1.setIcon(new ImageIcon(proC.abrirImagen()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         if(!proC.tieneImagen())
            return;
        proC.returnOriginal();
        jLabel1.setIcon(new ImageIcon(proC.imageActual));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(!proC.tieneImagen())
            return;
        muestraMatriz(proC.blur);
        jLabel1.setIcon(new ImageIcon(proC.blur()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(!proC.tieneImagen())
            return;
        muestraMatriz(proC.motionBlur);
        jLabel1.setIcon(new ImageIcon(proC.motionBlur()));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(!proC.tieneImagen())
            return;
        muestraMatriz(proC.edges);
        jLabel1.setIcon(new ImageIcon(proC.findEdges()));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(!proC.tieneImagen())
            return;
        muestraMatriz(proC.sharpen);
        jLabel1.setIcon(new ImageIcon(proC.sharpen()));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(!proC.tieneImagen())
            return;
        int[][] aux=new int[5][5];
        for(int i=0;i<5;i++)
            for(int j=0;j<5;j++)
                aux[i][j]=1;
        muestraMatriz(aux);
        jLabel1.setIcon(new ImageIcon(proC.mediana()));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String s1=v1.getText(),s2=v2.getText(),
                s3=v3.getText(),s4=v4.getText(),
                s5=v5.getText(),s6=v6.getText(),
                s7=v7.getText(),s8=v8.getText(),
                s9=v9.getText(),s10=v10.getText(),
                s11=v11.getText(),s12=v12.getText(),
                s13=v13.getText(),s14=v14.getText(),
                s15=v15.getText(),s16=v16.getText(),
                s17=v17.getText(),s18=v18.getText(),
                s19=v19.getText(),s20=v20.getText(),
                s21=v21.getText(),s22=v22.getText(),
                s23=v23.getText(),s24=v24.getText(),
                s25=v25.getText(),f=fact.getText(),
                b=bias.getText();
        int[][] m=new int[5][5];
        try{
            m[0][0]=Integer.parseInt(s1);
            m[0][1]=Integer.parseInt(s2);
            m[0][2]=Integer.parseInt(s3);
            m[0][3]=Integer.parseInt(s4);
            m[0][4]=Integer.parseInt(s5);
            m[1][0]=Integer.parseInt(s6);
            m[1][1]=Integer.parseInt(s7);
            m[1][2]=Integer.parseInt(s8);
            m[1][3]=Integer.parseInt(s9);
            m[1][4]=Integer.parseInt(s10);
            m[2][0]=Integer.parseInt(s11);
            m[2][1]=Integer.parseInt(s12);
            m[2][2]=Integer.parseInt(s13);
            m[2][3]=Integer.parseInt(s14);
            m[2][4]=Integer.parseInt(s15);
            m[3][0]=Integer.parseInt(s16);
            m[3][1]=Integer.parseInt(s17);
            m[3][2]=Integer.parseInt(s18);
            m[3][3]=Integer.parseInt(s19);
            m[3][4]=Integer.parseInt(s20);
            m[4][0]=Integer.parseInt(s21);
            m[4][1]=Integer.parseInt(s22);
            m[4][2]=Integer.parseInt(s23);
            m[4][3]=Integer.parseInt(s24);
            m[4][4]=Integer.parseInt(s25);
            if(!proC.tieneImagen())
               return;
            jLabel1.setIcon(new ImageIcon(
                    proC.convolution(m,Double.parseDouble(f),Double.parseDouble(b))));
        } catch(NumberFormatException e){
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    
    
    private void muestraMatriz(int[][] m){
        v1.setText(""+m[0][0]);
        v2.setText(""+m[0][1]);
        v3.setText(""+m[0][2]);
        v4.setText(""+m[0][3]);
        v5.setText(""+m[0][4]);
        v6.setText(""+m[1][0]);
        v7.setText(""+m[1][1]);
        v8.setText(""+m[1][2]);
        v9.setText(""+m[1][3]);
        v10.setText(""+m[1][4]);
        v11.setText(""+m[2][0]);
        v12.setText(""+m[2][1]);
        v13.setText(""+m[2][2]);
        v14.setText(""+m[2][3]);
        v15.setText(""+m[2][4]);
        v16.setText(""+m[3][0]);
        v17.setText(""+m[3][1]);
        v18.setText(""+m[3][2]);
        v19.setText(""+m[3][3]);
        v20.setText(""+m[3][4]);
        v21.setText(""+m[4][0]);
        v22.setText(""+m[4][1]);
        v23.setText(""+m[4][2]);
        v24.setText(""+m[4][3]);
        v25.setText(""+m[4][4]);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazConvolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazConvolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazConvolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazConvolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazConvolution().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bias;
    private javax.swing.JTextField fact;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField v1;
    private javax.swing.JTextField v10;
    private javax.swing.JTextField v11;
    private javax.swing.JTextField v12;
    private javax.swing.JTextField v13;
    private javax.swing.JTextField v14;
    private javax.swing.JTextField v15;
    private javax.swing.JTextField v16;
    private javax.swing.JTextField v17;
    private javax.swing.JTextField v18;
    private javax.swing.JTextField v19;
    private javax.swing.JTextField v2;
    private javax.swing.JTextField v20;
    private javax.swing.JTextField v21;
    private javax.swing.JTextField v22;
    private javax.swing.JTextField v23;
    private javax.swing.JTextField v24;
    private javax.swing.JTextField v25;
    private javax.swing.JTextField v3;
    private javax.swing.JTextField v4;
    private javax.swing.JTextField v5;
    private javax.swing.JTextField v6;
    private javax.swing.JTextField v7;
    private javax.swing.JTextField v8;
    private javax.swing.JTextField v9;
    // End of variables declaration//GEN-END:variables
}
